ru:
  # The display name of this language file
  this_file_language: "Русский"

  # Controllers
  resource_controller:
    saved: "Данные сохранены."
    removed: "Объекты успешно удалены."
    validation_errors: "Форма содержит ошибки. Для продолжения проверьте и исправьте пожалуйста введенные данные."
    update_conflict: "Данные были модифицированы с момента загрузки. Измененмя не могут быть сохранены т.к. возможна потеря информации."
  pages_controller:
    saved: "Страница сохранена."
    removed_many: "Страницы успешно удалены с сайта."
    removed_one: "Страница успешно удалена с сайта."
  preferences_controller:
    updated: "Ваши настройки сохранены"
    error_updating: "Ошибка при сохранении настроек."
  users_controller:
    cannot_delete_self: "Нельзя удалять себя."
  welcome_controller:
    logged_out: "Вы вышли из системы."
    invalid_user: "Неверное имя либо пароль."
    
  # Active Record
  activerecord:
    errors:
      messages:
        blank: 'обязательное поле' # required
        taken: 'имя ужк существует' # name_in_use
        not_a_number: 'должно быть числом' # must be number
        too_short: 'минимум {{count}} символов' # character_minimum
        too_long: 'ограничение {{count}} символов' # character_limit
        invalid: 'неверный формат' #invalid_format
      models:
        user:
          attributes:
            login:
              taken: 'Имя пользователя занято' # login_in_use
            password:
              confirmation: 'несоответствие подтверждению' # password_confirmation
            email:
              invalid: 'неверный адрес e-mail' # invalid_email
        page:
          attributes:
            slug:
              taken: 'окончание URL (slug) уже используется в иерархии страниц' # slug_in_use

  # Models
  models:
    # Model Names for validations
    user: 'User'
    page: 'Page'
    snippet: 'Snippet'
    layout: 'Layout'
    page_page: 'Page Part'
  
    # # Shared translations
    # required: 'обязательное поле'
    # name_in_use: 'имя ужк существует'
    # slug_in_use: 'окончание URL (slug) уже используется в иерархии страниц'
    # character_limit: 'ограничение {{count}} символов'
    # character_minimum: 'минимум {{count}} символов'
    # must_be_number: 'должно быть числом'
    # invalid_format: 'неверный формат'
    # no_spaces_tabs: 'не должно содержать пробелов м табудяций'
    # # User
    # login_in_use: 'Имя пользователя занято'
    # password_confirmation: 'несоответствие подтверждению'
    # invalid_email: 'неверный адрес e-mail'

  # Views
  views:
    shared:
      modify: 'Изменить'
      more: 'Дополнительно'
      less: 'Скрыть'
      body: 'Содержимое'
      name: 'Имя'
      filter: 'Фильтр'
      cancel: 'Отменить'
      or: '&nbsp;&nbsp;'
    extensions:
      extensions: 'Расширения'
      extension: 'Расширение'
      website: 'Веб сайт'
      version: 'Версия'
    # This is the rails application layout
    layout:
      made_with_ruby: 'Сайт создан на языке Ruby с использованием'
      version: 'Версия'
      users: 'Пользователи'
      extensions: 'Расширения'
      preferences: 'Настройки'
      view_site: 'Просмотр сайта'
      log_out: 'Выход'
    layouts:
      layouts: 'Макеты'
      layout: 'Макет'
      description: 'Примнняйте макеты для оформления страниц. Макеты могут содержать спец. тэги для вставки содержимого страниц и других элементов как заголовок и нижний колонтитул. Кликните на его имени макета для его редактирования млм <code>Remove</code> для удаления.'
      new_layout: 'Новый Макет'
      edit_layout: 'Редактирование Макета'
      content_type: 'Content&#8209;Type'
      remove_layout: 'Удалить Макет' #remove
      delete_layout: 'Удалить Макет' #delete
      remove_warning_text: 'Вы уверены что хотите <strong class="warning">безвозвратно удалить</strong> макет'
    page_parts:
      reference:  'Справка'
      available_tags: 'Доступные тэги'
    pages:
      pages: 'Страницы'
      page: 'Страница'   # Странмца vs. Страницу
      new_page: 'Новая Страница'
      edit_page:  'Редактирование Страницы'
      page_title: 'Заголовок'
      remove_tab: 'Удалить вкладку'
      add_tab: 'Добавить вкладку'
      status: 'Статус'
      page_type: 'Тип страницы'
      published_at: 'Опубликовано'
      close: 'Закрыть'
      no_pages: 'Нет страниц'
      delete_pages: 'Удалить {{pages}}'  #button
      remove_pages: 'Удалить {{pages}}'  #page title
      remove_warning_text: 'Вы уверены что хотите <strong class="warning">безвозвратно удалить</strong> {{pages}}?'
      available_tags_for: 'Тэги доступные для'
      search_tags: 'Поиск по тэгам:'
      add_part: 'Добавить Часть'
    snippets:
      snippets: 'Вставки'
      snippet: 'Вставка'
      new_snippet: 'Новая Вставка'
      edit_snippet: 'Редактирование Вставки'
      description: 'Вставки это небольшие части содержимого которые можно подключають к страницам или макетам.'
      remove_warning_text: 'Вы уверены что хотите <strong class="warning">безвозвратно удалить</strong> эту вставку?'
      delete_snippet: 'Удалить Вставку'
    users:
      user: 'Пользователь'
      users: 'Пользователи'
      username: 'Имя'
      password: 'Пароль'
      name: 'Имя'
      login: 'Логин'
      edit_user: 'Редактирование Пользователя'
      new_user: 'Новый Пользователь'
      roles: 'Роли'
      admin: 'Администратор'
      developer: 'Разработчик'
      language: 'Язык'
      notes: 'Заметки'
      optional: 'Опционально'
      required: 'Обязательно'
      valid_email: 'Введите действующий адрес e-mail.'
      valid_login: 'Не менее 3 символов. Должно быть уникально.'
      valid_password: 'Не менее 5 символов.'
      leave_password_unchanged: 'Оставьте пустым для сохранения старого пароля.'
      password_confirmation: 'Подтверждение Пароля'
      roles_description: 'Роли ограничивают права пользователей открывая и закрывая доступ к частям административного интерфеса.'
      language_description: 'Язык пользовательского интерфейса административной части.'
      remove_warning_text: 'Вы уверены что хотите <strong class="warning">безвозвратно удалить</strong> пользователя?'
      delete_user: 'Удалить Пользователя'
    preferences:
      user_preferences: 'Личные Настройки'
    welcome:
      login: 'Вход в систему'
      login_btn: 'Войти'
      remember_me: 'Запомнить меня'

  # Page status
  status:
    draft: 'Черновик'
    reviewed: 'Проверена'
    hidden: 'Скрыта'
    published: 'Опубликована'

  # Buttons
  buttons:
    save_and_continue: 'Сохранить и продолжить'
    save_changes: 'Сохранить'
    create: 'Создать' # removed {{name}} because of russian word cases problems 

  # Select lists
  select:
    none: '<none>'
    normal: '<normal>'
    inherit: '<inherit>'

  # Timestamp. This may need to be changed as it will most likely not work for many languages.
  timestamp:
    last_updated: 'Обновлено'
    by: 'пользователем'
    at: ''

  # Main Navigation Tags
  tabs:
    pages: 'Страницы'
    snippets: 'Вставки'
    layouts: 'Макеты'

  # Standard Tag Descriptions
  tag_desc:
    usage: 'Использование'
    produces: 'результат'

    page:
      desc: "Causes the tags referring to a page's attributes to refer to the current page."  #TODO: finish translation
      attributes: "Отображает аттрибут @{{method}}@ текущей страницы."
      url: "Отображает аттрибут @url@ текущей страницы."

    children: 
      desc: "Дает доступ к детям/наследникам страницы."
      count: "Отображает общее число детей/наследников."
      first: "Возвращает первого наследника. Внутри этого тэга все тэги являющиеся аттрибутами страницы применяются к первому наследнику.<br />
        Имеет возможности для упорядочивания аналогичные тегу @<r:children:each>@."
      last: "Возвращает последнего наследника. Внутри этого тэга все тэги являющиеся аттрибутами страницы применяются к последнему наследнику.<br />
        Имеет возможности для упорядочивания аналогичные тегу @<r:children:each>@."
      each: "Цикл по всем детям/наследникам. Внутри этого тэга все тэги являющиеся аттрибутами страницы применяются к текущему наследнику."
      child: "Тэги являющиеся аттрибутами страницы внутри этого тэга относятся к текущему наследнику. Это иногда удобно
        если внутри другого тэга (например &lt;r:find&gt;) нужно сослаться на текущего наследника."  
      if_first: "Отображает содержимое тэга только если текущая страница является первым наследником в контексте тэга &lt;children:each&gt;"
      unless_first: "Отображает содержимое тэга только если текущая страница является не первым наследником в контексте тэга &lt;children:each&gt;"
      if_last: "Отображает содержимое тэга только если текущая страница является последним наследником в контексте тэга &lt;children:each&gt;"
      unless_last: "Отображает содержимое тэга только если текущая страница является не последним наследником в контексте тэга &lt;children:each&gt;"
      header:
        p1: "Отображает содержимое тэга только если the contents do not match the previous header. This is extremely useful for rendering date headers for a list of child pages." #TODO: Finish translation
        p2: "If you would like to use several header blocks you may use the @name@ attribute to name the header. When a header is named it will not restart until another header of the same name is different."
        p3: "Using the @restart@ attribute you can cause other named headers to restart when the present header changes. Simply specify the names of the other headers in a semicolon separated list."

    parent: "Тэги являющиеся аттрибутами страницы внутри этого тэга относятся к родителю текущей страницы."
    if_parent: "Отображает содержащиеся элементы только если страница в текущем контексте имеет страницу родителя, т.е. не корневая страница."
    unless_parent: "Отображает содержащиеся элементы только если страница в текущем контексте не имеет страницу родителя, т.е. корневая страница."

    if_children: "Отображает содержащиеся элементы только если страница в текущем контексте имеет одну или
      более страниц наследников. Аттрибут @status@ ограничивает статус найденных страниц
      указанным статусом (по умолчанию @'published'@). @status='all'@ включает все невиртуальные страницы независимо от статуса."
    unless_children: "Отображает содержащиеся элементы только если страница в текущем контексте не имеет страниц наследников.
      Аттрибут @status@ ограничивает статус найденных страниц наследников указанным статусом,
      (по умолчанию @'published'@). @status='all'@ включает все невиртуальные страницы независимо от статуса."

    cycle: "Отображает одно из переданных значений на основании глобального счетчика цикла. Для сброса цикла в начало
      используется аттрибут @reset@. Для множественных циклов используется аттрибут @name@; имя по умолчанию -- @cycle@."
    content: "Отображает основное содержимое страницы. Используйте аттрибуты @part@ для выделения отдельных частей
      страницы. По умолчанию аттрибут @part@ установлен в @body@. Используйте аттрибут @inherit@
      для указания, что если страница не имеет части содержимого с таким именем то
      необходимо отобразить часть содержимого родителя. По умолчанию @inherit@ установлен в
      @false@. Используйте аттрибут @contextual@ для принудительной обработки наследованой у родителя части
      в контексте страницы наследника. По умолчанию аттрибут @contextual@ установлен в @true@."

    if_content:
      part_1: "Отображает содержащиеся элементы если все перечисленные части (part) присутствуют на странице.
        По умалчанию аттрибут @part@ эквивалентен @body@, но можно перечислить больше одного элемента
        разделяя их запятыми. Установка необязательного аттрибута @inherit@ в true обеспечивает
        поиск предков независимо для кажной части. По умолчанию @inherit@ установлен в @false@."
      part_2: "При указании более одной части можно установить необязательный аттрибут @find@ равным @any@
        для вывода содержащихся элементов в случае если хотя бы одна из перечисленных частей найдена.
        По умолчанию @find@ установлен в @all@."
    unless_content:
      part_1: "Тэг обратный тэгу @if_content@. Он отображает содержащиеся элементы если все
        перечисленные части (part) не присутствуют на странице. Установка необязательного аттрибута @inherit@ в true
        обеспечивает поиск предков независимо для кажной части. По умолчанию @inherit@ установлен в @false@."
      part_2: "При указании более одной части можно установить необязательный аттрибут @find@ равным @any@
        для того, чтобы не выводить содержащиеся элементы в случае если хотя бы одна из перечисленных частей найдена.
        По умолчанию @find@ установлен в @all@."

    if_url: "Отображает содержашиеся элементы только если URL страницы соответствует регулярному выражению
      указанному в аттрибуте @matches@. Если аттрибут @ignore_case@ установлен в false то проверка производится
      без учета регистра. По умолчанию @ignore_case@ установлен в true."
    unless_url: "Тэг обратный тэгу @if_url@."

    if_ancestor_or_self:
      part_1: "Отображает содержащиеся элементы если в текущем контексте либо сама страница либо один из ее предков."
      part_2: "Обычно используется внутри других тэгов (таких как &lt;r:children:each&gt;) для добавления условной разметки в случае если the child element is or descends from the current page." #TODO: finish translation
    unless_ancestor_or_self:
      part_1: "Отображает содержащиеся элементы в случаях кроме тех когда в текущем контексте либо сама страница либо один из ее предков."
      part_2: "Обычно используется внутри других тэгов (таких как &lt;r:children:each&gt;) для добавления условной разметки unless   the child element is or descends from the current page." #TODO: finish translation
    if_self:
      part_1: "Отображает содержащиеся элементы если в текущем контексте и есть сама страница."
      part_2: "Обычно используется внутри других тэгов (таких как &lt;r:children:each&gt;) для добавления условной разметки if the child element is the current page." #TODO: finish translation
    unless_self: 
      part_1: "Отображает содержащиеся элементы если в текущем контексте не сама страница."
      part_2: "Обычно используется внутри других тэгов (таких как &lt;r:children:each&gt;) для добавления условной разметки unless the child element is the current page." #TODO: finish translation

    author: "Отображает имя автора текущей страницы."

    date: "Отображает дату для текущей страницы (по умолчанию дату публикации или создания).
      Аттрибут format использует те же форматирующие коды, что и Ruby функция @strftime@.
      По умолчанию используется &#37;A, &#37;B &#37;d, &#37;Y. Аттрибут @for@ выбирает какую дату выводить.
      Возможные варианты: @published_at@, @created_at@, @updated_at@, и @now@. @now@ отобразит
      текущее время независимо от страницы."

    link: "Отображает ссылку на страницу. При использовании в качестве одиночного тэга он использует title страницы
      как имя ссылки. При использовании в качестве двойного тэга часть между двумя тэгами будет
      использована как текст ссылки. Тэг link передает всё аттрибуты в HTML
      тэг @a@. Это удобно для передачи таких аттрибутов как @class@ или @id@.
      В случае указания у тэга аттрибута @anchor@ к аттрибуту @href@ HTML тэга @a@ будет
      добавлен символ (<code>#</code>), а за ним значение аттрибута, что в результате дает HTML якорь."

    breadcrumbs: "Выводит цепочку ссылок для текущей страницы. Аттрибут 'separator'
      определяет фрагмент HTML вставляемый между ссылками цепи. По умолчанию он устанавлен в @>@.
      Логический аттрибут 'nolinks' может быть использован для вывода цепочки без ссылок
      (может быть полезно для генерации тэга title)."

    snippet:
      part_1: "Выводит вставку указанную в атрибуте @name@ в контексте страницы."
      part_2: "При использовании двойного тэга часть между тэгами может использоватся внутри самой вставки, заменяя @<r:yield/>@."

    yield:
      part_1: "Используется внутри вставок как место для вставки содержимого когда вставка вызывается двойным тэгом."
      usage: "Использование (внутри вставки):"
      part_2: "Если вставка приведенная выше имеет имя 'yielding', ее можно вызывать из любой Страницы, Макета или другой Вставки следующим образом:"
      part_3: "Что приведет к следующему результату:"
      part_4: "@<r:yield/>@ вызванный в контексте страницы или макета ничего не выводит."

    meta:
      desc: "Ru The namespace for 'meta' attributes. If used as a singleton tag, both the description and keywords fields will be output as &lt;meta /&gt; tags unless the attribute 'tag' is set to 'false'."  #TODO: finish translation
      keywords: "RU Emits the page keywords field in a meta tag, unless attribute 'tag' is set to 'false'."  #TODO: finish translation
      description: "Emits the page description field in a meta tag, unless attribute 'tag' is set to 'false'."  #TODO: finish translation

    status:
      desc: "Печатает статус страницы в виде строки. Необязательный аттрибут 'downcase' переводит статус в строчные буквы."

    unless_dev:
      desc: "Тэг обратный тэгу @if_dev@."

    if_dev:
      desc: "Выводмт содержащиеся элементы только если Radiant рвботает в development режиме."

    navigation:
      desc: "Отображает список ссылок указанных в аттрибуте @urls@ в соответствии с тремя состояниями: <br/>
        * @normal@ определяет обычное состояние ссылок<br/>
        * @here@ определяет состояние ссылки когда url соостетствует URL'ю текущей страницы<br/>
        * @selected@ указывает состояние ссылки когда текущая страница является наследником указанного url<br/>
        Тэг @between@ указывает что будет вставляться между ссылками."
        
      error: "тэг @navigation@ должен содержать тэг @normal@"

    rfc1123_date:
      desc: "Отображает дату публикации используя RFC 1123 формат (Идеально для RSS потоков)"

    escape_html:
      desc: "Заменяет угловые скобки и пр. для отображения внутри HTML документа."

    comment:
      desc: "Ничего, что помещено а тэг коментариев не выводится."

    random:
      desc: "Случайным образом отображает один из вариантов указанный в тэгах @option@."
    find:
      desc: "Внутри этого тэга все тэги указывают на страницу указанную в аттрибуте @url@. @url@ могут быть относительными или абсолютныии путями."

    markdown:
      desc: "Фильтрует содержимое используя Markdown фильтр."
    smarty_pants:
      desc: "Фильтрует содержимое используя SmartyPants фильтр."
    textile:
      desc: "Фильтрует содержимое используя Textile фильтр."


  date:
    formats:
      default: "%D-%M-%Y"
      short: "%e %b"
      long: "%B %e, %Y"
      only_day: "%e"

    day_names: [Воскресенье, Понедельник, Вторник, Среда, Четверг, Пятница, Суббота]
    abbr_day_names: [Вск, Пнд, Втр, Срд, "Чтв", Птн, Суб]
    month_names: [~, Января, Февраля, Марта, Апреля, Мая, Июня, Июля, Августа, Сентября, Октября, Ноября, Декабря]
    abbr_month_names: [~, Янв, Фев, Мар, Апр, Май, Июн, Июл, Авг, Сен, Окт, Ноя, Дек]
    order: [ :day, :month, :year ]

  time:
    formats:
      default: "%a %b %d %H:%M:%S %Z %Y"
      timestamp: "%d %B %Y в %H:%M"
      time: "%H:%M"
      short: "%d %b %H:%M"
      long: "%d %B %Y %H:%M"
      only_second: "%S"

      datetime:
        formats:
          default: "%Y-%m-%dT%H:%M:%S%Z"

    am: "am"
    pm: "pm"


ru: 
