#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: sqlite3
  database: db/radiant_dev.db
  
test: &TEST
  adapter: sqlite3
  database: db/radiant_test.db

production:
  adapter: sqlite3
  database: db/radiant_live.db
cucumber:
  <<: *TEST