development:
  adapter: sqlserver
  database: radiant_dev
  username:
  password:
  host:

test: &TEST
  adapter: sqlserver
  database: radiant_test
  username:
  password:
  host:

production:
  adapter: sqlserver
  database: radiant_live
  username:
  password:
  host:
    
cucumber:
  <<: *TEST